name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  platform-ci:
    uses: realdineomouessi1-pixel/platform-demo-lab1/.github/workflows/ci-realdineomouessi1-pixel.yml@main
    permissions:
      contents: read
      packages: write